# Generated by Django 5.0.3 on 2024-03-05 13:59

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('front_image', models.ImageField(upload_to=main.models.car_images_path)),
                ('back_image', models.ImageField(upload_to=main.models.car_images_path)),
                ('side_image', models.ImageField(upload_to=main.models.car_images_path)),
                ('interior_image', models.ImageField(upload_to=main.models.car_images_path)),
                ('engine_bay_image', models.ImageField(upload_to=main.models.car_images_path)),
                ('trunk_image', models.ImageField(upload_to=main.models.car_images_path)),
                ('features', models.ManyToManyField(to='main.feature')),
            ],
        ),
    ]
