# Generated by Django 5.0.3 on 2024-03-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_car_main_image_alter_car_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.URLField(),
        ),
    ]
