# Generated by Django 5.0.3 on 2024-03-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='Manual', max_length=50),
            preserve_default=False,
        ),
    ]
